version: "3"

services:
  web:
    build: ./client
    ports:
      - 5001:3000
    networks:
      - mern-network
    depends_on:
      - api
  api:
    build: ./server
    ports:
      - 5000:3001
    networks:
      - mern-network
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27016:27017
    networks:
      - mern-network
    env_file:
      - ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - database:/data/db

networks:
  mern-network:

volumes:
  database: